spring.application.name=demo
# spring.data.mongodb.uri=mongodb+srv://LMS_Tacniz:LMS_Tacniz@lmstacniz.zcczm.mongodb.net/libraryDB?retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://tacniz3:tacniz3@cluster0.h0cpn.mongodb.net/libraryDB?retryWrites=true&w=majority
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=librarymstacniz@gmail.com
spring.config.import=optional:classpath:hide.properties

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
